name: GitHub Actions Demo
on:
  push:
    branches:
    - main
    paths-ignore:
    - '.github'
  pull_request:
    branches:
    - main
  schedule:
  - cron: '15 6 * * 0'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run |
        echo "Event that triggered the workflow ${{ github.event_name }}"
        echo "Current branch: ${{ github.ref }}"

      - uses: actions/checkout@v3.3.0

      - name: Files in the repository
        run: |
          echo "Files in the repository ${{ github.repository }}"
          tree
  
